### PR TITLE
Move CQL generation into main function and enable better error reporting

### PR DESCRIPTION
**Pull request by bisscuitt**
The CQL you were using didn't work on my confluence, so I had to make it a bit more generic.

I also wanted to search in just a single space (my organisation has many spaces) so I added that functionality too.

This moves the CQL generation into the main function so it can be extended easily later.

### CODE REVIEW

**Comment by halkeye** [comment]
oh wow, sorry @bisscuitt I totally never saw this.

**Review by halkeye — CHANGES_REQUESTED** [review]
Can you add the HUBOT_CONFLUENCE_SEARCH_SPACE to the top of the .js file in the comments as well?

And conflicted about the console.log being kept in. I kinda like the idea of not being verbose unless its enabled.

**Comment by bisscuitt** [comment]
@halkeye - I've updated with the requested changes...

Perhaps if we both keep responding at such a rapid pace then we can get this merged by Christmas !!! ;) :santa:

**Review by halkeye — COMMENTED** [review]
Woo, looks good to me.

I'm a little concerned about the error message now beinh super verbose but shouldn't be an issue

Merging

**Comment by halkeye** [comment]
I'll try to remember to cut a release tomorrow

That's well before Christmas

**Comment by halkeye** [comment]
published hubot-confluence-search@1.1.0

**Comment by bisscuitt** [comment]
:metal: Thanks man! :) Christmas has come early !! ;) :christmas_tree:

**Pull request merged**
